      - name: Show generated APKs
        run: |
          echo "Searching for APK files..."
          find build-project -type f -name "*.apk" -print

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Papa-Chlm-APKs
          path: |
            build-project/**/*.apk
          if-no-files-found: error
